### ISSUE TITLE
Sort order issue

### ISSUE THREAD

**Issue by ghost** [tute/phpscaffold#1]
Hello,

here the code is only working if inc.functions.php line 200 is changed in:
return 'ORDER BY ".$default."';

**Comment by tute** [comment]
Do you get an error? If so, could you please paste it? Here it was working ok!
Thanks for your time.

**Comment by ghost** [comment]
Yes, I got an SQL error, because the variable is not replaced by the value of the variable. With the code above it works

**Comment by tute** [comment]
You are right, solved it in http://github.com/tute/phpscaffold/commit/a763dc2fa2f0878f80bd86cf8ec7b2fa234e3a3e . Thanks for your time, mySeat!
