### ISSUE TITLE
inc.paging.php wrong count

### ISSUE THREAD

**Issue by ghost** [tute/phpscaffold#2]
Hello,
in inc.paging.php line 5 the generated code has always "COUNT(id)" instead of the individual name of the id field e.g.:
$num_results = mysql_result(mysql_query('SELECT COUNT(user_id) AS tot FROM `users` WHERE ' .  $conds), 0);

**Comment by tute** [comment]
Thank you, mySeat. To read the id key column we could search for the "auto_increment" line, and grab the column name. I can not check it out now, but thanks for the tip!

**Comment by tute** [comment]
Solved in commit http://github.com/tute/phpscaffold/commit/ac1750c2ea4657434b703fc56d4f140c7c26c2cc .
Thank you again, mySeat!
