### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by arpori** [tute/phpscaffold#4]
Parse error: syntax error, unexpected '"' in C:\wamp\www\tes\tute\lib\scaffold.php on line 19
how to fix??

**Comment by tute** [comment]
I don't get that error. If in `lib/scaffold.php:19` you change

```
        $return_string = "<?php
include('../inc.functions.php');\n";
```

by

```
        $return_string = "<?php\ninclude('../inc.functions.php');\n";
```

Error message changes? In that case we may have to change all strings with "real" new lines, can't see why though.

**Comment by arpori** [comment]
still get error
Parse error: syntax error, unexpected '"' in C:\wamp\www\tes\phpscafold\lib\scaffold.php on line 80
please help me..

**Comment by tute** [comment]
Then we need to write \n instead of "real" new lines on each string which have them. Error messages tell you where they are to fix them. If you want to send a pull request, I'll help you with it!
Thanks for reporting,
Tute.

**Comment by arpori** [comment]
How to do pull request?

**Comment by tute** [comment]
Fork the project (I've seen you did!), make the changes to the files needing this fix, commit and push it (do you know Git?). Then you can send pull requests through Github.
Thank you again!
