### ISSUE TITLE
DOS end of lines - Translations

### ISSUE THREAD

**Issue by demonarg** [tute/phpscaffold#7]
Hi tute! I've been using these project and I found some strange DOS "end of line" in all de inc php files.

How do you create or edit theses files? Because I try to convert the files with dos2unix but if I do that I have to pull all the source code again...

--- a/lib/statics/inc.auth.php
+++ b/lib/statics/inc.auth.php
@@ -9,7 +9,7 @@ if (isset($_POST['user']) && isset($_POST['pass'])) {
                exit;
        } else {
                unset($_SESSION['user_logged_in']);
-               $msg = 'Sorry, wrong user id or password.';
-               $msg = 'Disculpas, usuario o contrase&ntilde; incorrectos.';^M
      }
  }

BTW I'm translating all the text and messages to spanish ;)

**Comment by tute** [comment]
Hi @demonarg! Thanks for helping. I don't understand the problem, who is raising that error? When? What does it mean "pull all the source again"? It makes sense to have a gigantic diff if you are doing white space fixes (when checking with `git log` or `git diff`, you can disable white space changes easily to see there were no "real" changes, you have just to make one single commit with that fix so I can merge it safely).

On translating, isn't there a good PHP I18n library? So phpscaffold doesn't belong to any language by itself, but it support many. If not, we'll have to mantain 2 different branches.

All the best,

Tute.

**Comment by tute** [comment]
Seems like for translations we may play with http://php.net/manual/es/book.gettext.php

But let's not change the current strings if not for "abstracting" them, or we'll introduce the same "issue" of being tied to a concrete language.

**Comment by demonarg** [comment]
Hi tute!

> I don't understand the problem, who is raising that error? When? 

For example,  I've made a simple clone of your repo and then start a fork to translate the text and messages to spanish (later we can discuss how to pull those changes).

So, I start editing the files only with the vi but when I try to pull the changes I found a strange DOS "^M" character at the end of the line (maybe is my git client?)

> What does it mean "pull all the source again"? It makes sense to have a gigantic diff if you are doing white space fixes (when checking with git log or git diff, you can disable white space changes easily to see there were no "real" changes, you have just to make one single commit with that fix so I can merge it safely).

If I ran the dos2unix tool over your code I have differences in every line because I've change the end of line, at least that make sense for me.
I try this examples too
http://www.brandonhutchinson.com/DOS_and_UNIX_end-of-line_characters.html

> On translating, isn't there a good PHP I18n library? So phpscaffold doesn't belong to any language by itself, but it support many. If not, we'll have to mantain 2 different branches.

Sure! If you know how to do it tell me...
PS I would like to translate to chileno when you came back to argentina, if you know what I mean ;)

**Comment by demonarg** [comment]
> Seems like for translations we may play with http://php.net/manual/es/book.gettext.php

That it's exactly what we need.

> But let's not change the current strings if not for "abstracting" them, or we'll introduce the same "issue" of being tied to a concrete language.

If we want to start using l18nt at least we need to identify every message and start using gettext

http://theclimber.fritalk.com/post/2009/09/16/i18n-gettext-for-your-PHP-application
"First you need to change your code and to use Gettext for all you translatable strings."

There is some more information in the GNU project about manipulating PO files
http://www.gnu.org/software/trans-coord/manual/gnun/html_node/PO-Files.html

Thanks!

**Comment by tute** [comment]
> [...] I found a strange DOS "^M" character at the end of the line.
> If I ran the dos2unix tool over your code I have differences in every line because I've change the end of line, at least that make sense for me.

I'll happily merge a pull request with this end-of-line fixes (with only white space changes). I understand it will 
be a huge diff. You can check it's only white space using `git log` with the `--ignore-space-change` or `-b` flag. While "^M" characters are harmless, I don't like them either.

> If we want to start using l18n at least we need to identify every message and start using gettext

Exactly. So, if we changed strings, they'll be I18n function calls. As `.po` files seem like plain text I don't see a problem in using it, but I'd like it to have more structure (like with YML, JSON, or whatever) so we can have categories of strings. Don't know if there are good libraries for that, if not, I would go with `.po` files.

> PS I would like to translate to chileno when you came back to argentina, if you know what I mean ;)

Yo cacho muy bien lo que tú me hablái, pero creo que nos conocemos y que soi un huevón por no presentarte! :-)
